### PR TITLE
Added conditionals to swap video and add a disclaimer on first lesson

### LINKED ISSUE #31: Add temporary note and workaround for inaccessible video
## Description

Since the first video is still unavailable, we can temporarily link the video from class 01 with notes on the differences and a short explanation.

### Steps:
- Add a clear message on the page where the first video was. Let students know we're using an older video temporarily.
- Include a disclaimer in the message saying that the original video's removal is under dispute, and we're not certain who made the claim as that is also under dispute.
- Link the video from our older cohort 01 series. Make sure to explain that it's from an earlier series and there may be some differences in content.
- Emphasize that the main goal is to start working on the 'Learning to Learn' course homework.
- Also, let's link to Leon's Twitter post that explains the situation for students who want more context on this issue.

### Notes:
We should also be ready to quickly revert this change as soon as the video is restored with a follow up note that it is now working. 

🙋 I am willing to take on this issue if you would like to assign it to me.

### PR DESCRIPTION
**Pull request by intelagense**
## Description

I've implemented conditional statements to check for the missing video ID. When a match is found, the video is swapped, and a brief disclaimer is added. 

This method, while differing from the initial suggestion in #31, I believe, minimizes user confusion by keeping them on the same page, rather than redirecting them to a new page or YouTube. 

This approach is not only straightforward to reverse or modify in the future but also was more manageable to implement without needing extensive knowledge of pug.js.

Please let me know if this solution is acceptable, or if I should instead proceed with adding a separate route and page as initially proposed.

Closes #31 

image

### CODE REVIEW

**Comment by labrocadabro** [comment]
Works for me, can you just do two things:

1) In the disclaimer add a "more info" link that goes to Leon's twitter message.

2) Change the title of this PR so that it's linked to the issue. Just add "closes #31" and that should do it.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by intelagense** [comment]
I stumbled on a typo, but the link has been added and it looks like it is properly linked now through the last commit message.

**Review by labrocadabro — APPROVED** [review]

**Comment by labrocadabro** [comment]
I didn't want to quibble about the issue linking as it wasn't that important. But for future reference, you have to put it in the title rather than the description.

**Comment by labrocadabro** [comment]
Oh uh never mind, apparently the descriptions works too haha.

**Comment by 20jasper** [comment]
@intelagense LET"S GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
